GET http://localhost:3000/



###
 var  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo0LCJjaGF0SWQiOiIxMTEiLCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6bnVsbCwicGhvbmUiOiJxYXoiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNC0wOS0yOFQwMDo0OTozOC4wMDFaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0yOFQwMDo0OTozOC4wMDFaIiwicm9sZUlkIjozfSwic3ViIjo0LCJpYXQiOjE3Mjc0ODQ4NTQsImV4cCI6MTcyNzQ4ODQ1NH0.OGuxE8ynb0LCibqExbFioq03if20nJV9QaERRkRlBSI"



###
GET http://localhost:3000/users


###
POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
    "phone": "qaz",
    "password": "aezakmi"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Joe Biden",
    "phone": "1234567890",
    "password": "1234567890",
    "chatId": "123",
    
}



###
# const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTcyMjYyNjYyOCwiZXhwIjoxNzIyNjI2Njg4fQ.4555555555555555555555555555555555555555555555555555555555555555"

###
GET http://localhost:3000/users/
Content-Type: application/json
# Authorization: Bearer {{token}}

{
    "userId": 2
}


###
POST  http://localhost:3000/auctions/updateimg
Content-Type: application/json

{
    "id": 6,
  "imageType": "GALERY",
  "images": [
    "https://tgab-imgstore.s3.eu-north-1.amazonaws.com/img/6/8ddf6a93c78c4ad0be42903b6ba5ada2l0vpIhYh9bM0xN0N-3.png",
    "https://tgab-imgstore.s3.eu-north-1.amazonaws.com/img/6/8ddf6a93c78c4ad0be42903b6ba5ada2l0vpIhYh9bM0xN0N-4.png",
    "https://tgab-imgstore.s3.eu-north-1.amazonaws.com/img/6/8ddf6a93c78c4ad0be42903b6ba5ada2l0vpIhYh9bM0xN0N-5.png"
  ],
  "primary": "https://tgab-imgstore.s3.eu-north-1.amazonaws.com/img/6/8ddf6a93c78c4ad0be42903b6ba5ada2l0vpIhYh9bM0xN0N-3.png"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Jony be Good2",
    "email": "johndjonyoe@mail.com",
    "chatId": "1234567300"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "phone": "qaz",
    "pass": "aezakmi"
}

### 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Joe Biden",
    "phone": "1234567890",
    "pass": "1234567890"
}

###
GET http://localhost:3000/auctions

###
GET http://localhost:3000/auctions/2

###
POST http://localhost:3000/auctions/
Content-Type: application/json

{
    "title": "Some Event 78225",
    "startPrice": 455.56,
    "startTime": "2024-09-26T15:58:30Z",
    "endTime": "2024-09-26T18:58:30Z"
    
}


###
GET http://localhost:3000/bids/getFew
Content-Type: application/json

{
    "userId": 2,
    "count": 3
    
}

###
POST http://localhost:3000/bids/getFew
Content-Type: application/json

{
    "auctionId": 1,
    "count": 15
    
}

###
POST http://localhost:3000/bids/add
Content-Type: application/json

{ 
    "auctionId": 1,
    "userId": 2,
    "amount": 150.2
}